name = "media-downloader-bot"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "e9928dade1387a975ceeea440a1c0e80"

[vars]
ADMIN_IDS = "693732696"

[[d1_databases]]
binding = "DB"
database_name = "media-downloader-bot-db"
database_id = "REPLACE_AFTER_D1_CREATE"
